name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login docker
      run: docker login -u lkk654321tw -p simon561220
      
    - name: build coredns
      run: docker build . --file coredns/Dockerfile --tag lkk654321tw/docker-images:coredns-1.6.7
    - name: push coredns  
      run: docker push lkk654321tw/docker-images:coredns-1.6.7
      
    - name: build defaultbackend-amd64
      run: docker build . --file defaultbackend-amd64/Dockerfile --tag lkk654321tw/docker-images:defaultbackend-amd64-1.5
    - name: push defaultbackend-amd64
      run: docker push lkk654321tw/docker-images:defaultbackend-amd64-1.5
